ADCIRC: &adcirc
  AdcircGrid: "hsofs"
  Machine: "hatteras.renci.org"
  NodeList: "adcirc_test_nodes.dat"
  Instance: "hsofs-nam-bob"  #  "ncfs-dev-hsofs-nam-master"
  baseurl: "http://tds.renci.org:8080/thredds/"
  catPart: "/catalog/2020/nam/catalog.xml"
  #                 year    /ymd,c/grid/machine/...
  # http://tds.renci.org:8080/thredds/dodsC/2020/nam/2020012706/hsofs/hatteras.renci.org/ncfs-dev-hsofs-nam-master/namforecast/maxele.63.nc
  # http://tds.renci.org:8080/thredds/dodsC/2020/nam/2020012706/hsofs/hatteras.renci.org/ncfs-dev-hsofs-nam-master/namforecast/maxele.63.nc
  #dodsCpart: "/dodsC/%s/nam/%s/%s/%s/%s/nowcast/fort.%s.nc"
  dodsCpart: "/dodsC/%s/nam/%s/%s/%s/%s/namforecast/fort.%s.nc"
  fortNumber: "63"

TIME: &time
  T1: 0        # datetime or negative for lag from T2 Can set this to >0 and specify timein to look forward
  T2: +4         # datetime for end date or 0 for "now"
  # doffset: 4     # multiple of M2 cycles to do averaging over

REGRID: &regrid
  InterpToAdcirc: true
  RECT:
    lowerleft_x: -100
    lowerleft_y: 20
    res: .1  # resolution in deg
    nx: 400
    ny: 300

