--- #  Compute errors and interpolate

# This is a convenience entry to facilitate some basic diagnostic graphing

DEFAULT: &DEFAULT
  ClampList: "water_control_list.dat"
  ControlList: "land_control_list.dat"

REGRID: &regrid
  InterpToAdcirc: true
  RECT:
    lowerleft_x: -100
    lowerleft_y: 20
    res: .1  # resolution in deg
    nx: 400
    ny: 300

KRIGING: &kriging
   VPARAMS:
      sill: 0.015 # 2
      range: 8 # 2 
      nugget: 0.05 # 0.1
   PARAMS:
      method: "ordinary"
      variogram_model: "gaussian"
      coordinates_type: "geographic"
      weight: True
      nlags: 6 

CVKRIGING: &cvkriging
   VPARAMS:
      sill: [0.016, 0.05, 0.1, 0.2]
      range: [2, 3, 5, 10] # , 20]
      nugget: [0.005, 0.05, 0.1, 0.2, 0.3]
   PARAMS:
      method: ["ordinary"]
      variogram_model: ["gaussian"] # , "spherical"]
      coordinates_type: ["geographic"]
      weight: [True]
      nlags: [6, 8, 10]
