# This is a convenience entry to facilitate some basic diagnostic graphing 
DEFAULT: &DEFAULT
  ClampList: "clamp_list_hsofs_nobox.dat"
  ControlList: "control_list_hsofs.dat"

REGRID: &regrid
  InterpToAdcirc: true
  RECT:
    lowerleft_x: -100
    lowerleft_y: 5 
    res: .1  # resolution in deg
    nx: 500
    ny: 400

KRIGING: &kriging
   VPARAMS:
      sill: 0.16 # 0.2
      range: 8 # 2
      nugget: 0.001 # 0.1 
   PARAMS:
      method: "ordinary"
      variogram_model: "gaussian"
      coordinates_type: "geographic"
      weight: True
      nlags: 6

CVKRIGING: &cvkriging
   VPARAMS:
      sill:  [0.01, 0.02, 0.05] # [.1, .2, .3, .5, 1., 2., 5., 10.]
      range: [2, 10, 20 ]
      nugget: [0.05, 0.1,0.2,0.3]
   PARAMS:
      method: ["ordinary"] # Note ordinary and universal have different variables
      variogram_model: ["spherical", "gaussian"]
      coordinates_type: ["geographic"]
      weight: [False,True]
      nlags: [6, 10, 20]
