--- #  Compute errors and interpolate

# This is a convenience entry to facilitate some basic diagnostic graphing

DEFAULT: &DEFAULT
  ClampList: "clamp_list_hsofs.dat"

REGRID: &regrid
  InterpToAdcirc: true
  RECT:
    lowerleft_x: -100
    lowerleft_y: 20
    res: .1  # resolution in deg
    nx: 400
    ny: 300

KRIGING: &kriging
   VPARAMS:
      sill: 0.1
      range: 6 
      nugget: 0.05
   PARAMS:
      method: "ordinary"
      variogram_model: "gaussian"
      coordinates_type: "geographic"
      weight: True
      nlags: 10  

CVKRIGING: &cvkriging
   VPARAMS:
      sill: [.1, .2, .3]
      range: [6,10,20]
      nugget: [0.05, 0.1, 0.2, 0.3]
   PARAMS:
      method: ["ordinary"]
      variogram_model: ["gaussian", "spherical"]
      coordinates_type: ["geographic"]
      anisotropy_scaling: [1]
      anisotropy_angle: [0]
      weight: [True, False]
      nlags: [5, 10, 20]
