--- # adcirc DA config file
DEFAULT: &default
  PHOME: $ADCIRCSupportHome     #  this is currently ignored
  RDIR: $RUNTIMEDIR   
  LOGGING: true
  LOGLEVEL: DEBUG
  GRAPHICS: true

GRAPHICS: &graphics
  CMAP: "bwr"
  NCOL: 20
  VMIN: -0.5
  VMAX: 0.5
  MAPRES: "i"

STATIONS: &stations
  HSOFS: "CERA_NOAA_HSOFS_stations_V2.csv"
  EC95D: "ec95d_stations.V1.csv"
  REGION3: "Region3_Stations_V2.csv"
  NC_INUNDATION_V9.99_W_RIVERS: "NCV99_Stations_V1.csv"
  NC_INUNDATION_V9.99D: "NCV99_Stations_V1.csv"
  LA_V20A-WITHUPPERATCH_CHK: "LA_v20a-WithUpperAtch_chk_Stations_V1.csv"
  URIV18: "uriv18_stations_V1.csv"
  URIV18_CL: "uriv18_stations_V1.csv"
  NCSC_SAB_V1.15: "NCSC115_stations_V1.0.csv" 
  NCSC_SAB_V1.20: "NCSC120_stations_V1.0.csv"
  NCSC_SAB_V1.22: "NCSC122_stations_V1.0.csv"
  NCSC_SAB_V1.23: "NCSC123_stations_V1.0.csv"
  SABV20A: "SABv20a_stations_V1.0.csv"
  EGOMV20B: "EGOMv20b_stations_V1.csv"
