--- # adcirc DA config file
DEFAULT: &default
  PHOME: $ADCIRCSupportHome     #  this is currently ignored
  RDIR: $RUNTIMEDIR   
  LOGGING: true
  LOGLEVEL: DEBUG
  GRAPHICS: true

GRAPHICS: &graphics
  CMAP: "bwr"
  NCOL: 20
  VMIN: -0.5
  VMAX: 0.5
  MAPRES: "i"

STATIONS: &stations
  HSOFS: "CERA_NOAA_HSOFS_stations_V2.csv"
  EC95D: "ec95d_stations.V1.csv"
  REGION3: "Region3_Stations_V1.csv"
