DEFAULT: &default
  StationFile: "ec95d_stations.V1.csv"

OBSERVATIONS: &observations
  EX_COOPS_NANS: True
  EX_MULTIVALUE: False
  EX_THRESH: False # True
  THRESH: 10
  DATUM: "MSL"
  UNIT: "metric"
  TIMEZONE: "gmt"
  PRODUCT: "hourly_height" # "water_level"
  STATIONS: [8410140, 8413320, 8418150] 
