--- #  Compute errors and interpolate
DEFAULT: &default
    ClampList: "clamp_list_hsofs.dat"

TIME: &time
  T1: -4        # datetime or negative for lag from T2
  T2: 0         # datetime for end date or 0 for "now"
  AvgPer: 4     # multiple of M2 cycles to do averaging over
  n_period: 12  # Number of values per period (hourly =12)
  n_tide: 12.42 # semidiurnal time period
  n_pad: 1      # Number of extra steps to include for interpolating into tide time

ERRORFIELD: &errorfield
  EX_OUTLIER: True

# This is a convenience entry to facilitate some basic diagnostic graphing
REGRID: &regrid
  InterpToAdcirc: true
  RECT:
    lowerleft_x: -100
    lowerleft_y: 20
    res: .1  # resolution in deg
    nx: 400
    ny: 300


KRIGING: &kriging
   VPARAMS:
      sill: 2
      range: 2
      nugget: 0.1
   PARAMS:
      method: "ordinary"
      variogram_model: "gaussian"
      coordinates_type: "euclidean"
      weight: True
      nlags: 2

CVKRIGING: &cvkriging
   VPARAMS:
      sill: [1, 2, 3]
      range: [1, 2, 3]
      nugget: [0.05, 0.1, 0.2, 0.3]
   PARAMS:
      method: ["ordinary", "universal"]
      variogram_model: ["exponential", "gaussian", "spherical"]
      coordinates_type: ["euclidean","geographic"]
      anisotropy_scaling: [1]
      anisotropy_angle: [0]
      weight: [True, False]
      nlags: [1, 2, 4, 6, 8]
